name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore Backend/WebMedicalApplication/WebMedicalApplication.csproj

    - name: Build
      run: dotnet build Backend/WebMedicalApplication/WebMedicalApplication.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Backend/WebMedicalApplication/WebMedicalApplication.csproj --configuration Release --no-restore --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: BackendMedicalApplication
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
